theme = "blowfish"
baseURL = "http://arise-net.github.io/"
defaultContentLanguage = "en"

enableRobotsTXT = true
pagination.pagerSize = 10

enableGitInfo = true

[params]
  customCSS = ["css/custom.css"]

[params.list]
  cardView = true
  showCardImage = true
  
[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"