# Global
tile = "ARISE Website"
languageCode = "en"
languageName = "English"
weight = 1

# Params
[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "images/logo/Logo_Branco.png"
  secondaryLogo = "images/logo/Logo_Preto.png"
  description = "ARISE Website - Aquatic Research for Impact, Sustainability and Evidence"
  copyright = "Â© 2026 ARISE"

[params.author]
  name = "Aquatic Research for Impact, Sustainability and Evidence"
  email = "tai.loureiro@uwa.edu.au"
  headline = ""
  links = [
    { github = "https://github.com/arise-net" }
  ]
