[[main]]
none = "none"

[[main]]
pageRef = "About"
identifier = "about"
weight = 10

[[main]]
pageRef = "People"
identifier = "people"
weight = 20

[[main]]
pageRef = "Projects"
identifier = "projects"
weight = 30

[[main]]
pageRef = "Resources"
identifier = "resources"
weight = 40

[[main]]
pageRef = "Contact"
identifier = "contact"
weight = 50
