# Global
enablePWA = false # to avoid Progressive Web App (PWA)
colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = false
replyByEmail = false
backgroundImageWidth = 1200
disableTextInHeader = true
defaultBackgroundImage = "images/back/IMG_20240718_063957.jpg"

# Header
[header]
  layout = "fixed"
  
# Footer
[footer]
  showMenu = false
  showCopyRight = true
  showThemeAttribution = true
  showAppearanceSwitcher = true # shows in the header
  
# Homepage
[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  showRecent = false
  cardView = true
  layoutBackgroundBlur = true
  
# Article - pages like about, using /index.md
[article]
  showDate = false
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = false
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = false # only used when heroStyle equals background
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = false
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = false
  showAuthorsBadges = false
  showWordCount = false
  showSummary = true
  sharingLinks = false
  cardImageRatio = "16x9"

# List - pages like People and Projects, using /_index.md
[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showSummary = true # in projects, for ex, summary of each project
  showTableOfContents = false
  cardView = false
  showCardImage = true
  constrainItemsWidth = false # constrain text in projects text for ex
  groupByYear = false # if set to true and there's no date it displays 0001 above cards


# Sitemap

# Taxonomy - groupings of content - taxonomie, terms and values
# for ex: 
# Actor                    <- Taxonomy
#    Bruce Willis         <- Term
#        The Sixth Sense  <- Value
#        Unbreakable      <- Value
#        Moonrise Kingdom <- Value
#    Samuel L. Jackson    <- Term
#        Unbreakable      <- Value
#        The Avengers     <- Value
#        xXx              <- Value
        
# Term

# Firebase

# Analytics

# BuyMeACoffee

# Verifications
#[verification]
#  google = "The site verification string provided by Google to be included in the site metadata."

# RSSNext
#[rssnet]
#  feedId = "The rss feedId string provided by RSSNext/Follow to be included in the rss.xml, which can helps to claim rss feed as your own."
#  userId = "The rss userId string provided by RSSNext/Follow to be included in the rss.xml, which can helps to claim rss feed as your own."

# Advertisement
#[advertisement]
#  adsense = "Your Google AdSense Publisher ID (e.g. ca-pub-1234567890abcdef). Set this parameter to enable AdSense ads on your site."
  